name: "Environmental"
on:
    push:
        branches:
            - dev
jobs:
    build:
        environment: ${{ github.event_name.environment == 'development' }}
        runs-on: ubuntu-latest
        steps:
            - name: Chekout Repo
              uses: actions/checkout@v4

