name: "Environmental"
on:
    push:
        branches:
            - dev
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Chekout Repo
              uses: actions/checkoutrepo@v4

