name: "Environmental"
on:
    push:
        branches:
            - dev
            - stage

            
jobs:
    Dev:
        name: Dev Environment
        if: ${{ github.ref == 'refs/heads/dev' }}
        environment:
            name: dev
        runs-on: ubuntu-latest
        steps:
            - name: Chekout Repo
              uses: actions/checkout@v4

            - name: Install Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.7.0

            - name: Aws Configuration
              run: bash Scripts/aws_configure.sh
              env:
                AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
                AWS_PROFILE: ${{secrets.AWS_PROFILE}}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}



              
    Stage:
        name: Stage Environment
        if: ${{ github.ref == 'refs/heads/stage' }}
        environment:
            name: stage
        runs-on: ubuntu-latest
        steps:
            - name: Checkout-repo
              uses: actions/checkout@v4
            
            - name: Install Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.7.0

            - name: Aws Configuration
              run: bash Scripts/aws_configure.sh
              env:
                AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
                AWS_PROFILE: ${{secrets.AWS_PROFILE}}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  