name: "Environmental"
on:
    push:
        branches:
            - dev
jobs:
    build:
        environment:
            name: developement

        runs-on: ubuntu-latest
        steps:
            - name: Chekout Repo
              uses: actions/checkout@v4

